### ISSUE TITLE
Inconsistent ssh results through jetstream script

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/jetstream-scripts#5]
I get this weird behaviour:

```
[17:55:53] ~/Dropbox/.../jetstream> ./jetstream ssh marc-test2
Connecting to 149.165.171.188
ssh: connect to host 149.165.171.188 port 22: Connection refused
[17:56:18] ~/Dropbox/.../jetstream> ./jetstream ssh 149.165.171.188
Connecting to 149.165.171.188
The authenticity of host '149.165.171.188 (149.165.171.188)' can't be established.
ECDSA key fingerprint is SHA256:GRzKxcYkt9hTHU6vfarLJ2IhAxkJWBbrAWFNv7mG7xI.
```

With the name it fails, even though it finds the right IP address, but with the IP address it succeeds after I okay the host.

**Comment by ksuderman** [comment]
That is weird...  does this happen consistently? If you use the name it simply looks up the IP address and then connects to that, so in the end both commands do `jetstream ssh <ip address>`. 

Could it be that you tried to ssh into the instance before it had finished starting?

**Comment by marcverhagen** [comment]
It does appear to be consistent. The behaviour I get this morning is slightly different in that the keys have changed, but it is still different from name to IP address:

```
[10:43:34] ~/Dropbox/.../jetstream> ./jetstream ssh marc-test
/Applications/ADDED/other/miniconda2/lib/python2.7/site-packages/novaclient/client.py:278: UserWarning: The 'tenant_id' argument is deprecated in Ocata and its use may result in errors in future releases. As 'project_id' is provided, the 'tenant_id' argument will be ignored.
  warnings.warn(msg)
Connecting to 149.165.171.188
ssh: connect to host 149.165.171.188 port 22: Connection refused
[10:43:43] ~/Dropbox/.../jetstream> ./jetstream ssh 149.165.171.188
Connecting to 149.165.171.188
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:M3//wD9vW8OqufjgUz0kZgBJUb6VFStjQJGRei1BURY.
Please contact your system administrator.
Add correct host key in /Users/marc/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/marc/.ssh/known_hosts:67
ECDSA host key for 149.165.171.188 has changed and you have requested strict checking.
Host key verification failed.
```

**Comment by ksuderman** [comment]
That is truly bizarre...  in either case (name or ip address) the same line of the script gets executed, and the script always uses the ip address.  So the result should be exactly the same.  I can't reproduce the problem so I want to suspect something different on your system.  But I can't imagine what would make `ssh -i $PEM root@$IP` behave differently...

**Comment by marcverhagen** [comment]
The cause was two faulty lines in my known_hosts file. Removing those lines made `jetstream launch` work the same for the name and the ip address.

**Comment by marcverhagen** [comment]
Out of interest's sake we may want to play with screwing up lines in known_hosts and figure out what exactly is going on.
