### ISSUE TITLE
Failure locating emacs and openjdk-8-jdk

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/jetstream-scripts#6]
When I run one-step-install I get two errors:

```
E: Package 'emacs' has no installation candidate
E: Unable to locate package openjdk-8-jdk
```

The script happily continues after the first but terminates after the second. This is on a vanilla instance created from the default ubuntu image.

**Comment by ksuderman** [comment]
Both issues have been fixed. The name of the emacs package should be emacs24-nox on Ubuntu and OpenJDK 8 isn't in the default Ubuntu repo so needs a separate repo (ppa) configured.

Note that the one-step-install.sh has been renamed to setup.sh and now lives in the service-manager-installation repository.
