### ISSUE TITLE
jetstream forget fails on some known_hosts files

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/jetstream-scripts#7]
When I run `jetstream forget` using the script in the keith branch I get the following: 

```
[10:53:43] ~/Dropbox/.../jetstream> ./jetstream forget marc-test
Getting ip address for marc-test
/Applications/ADDED/other/miniconda2/lib/python2.7/site-packages/novaclient/client.py:278: UserWarning: The 'tenant_id' argument is deprecated in Ocata and its use may result in errors in future releases. As 'project_id' is provided, the 'tenant_id' argument will be ignored.
  warnings.warn(msg)
/Applications/ADDED/other/miniconda2/lib/python2.7/site-packages/novaclient/client.py:278: UserWarning: The 'tenant_id' argument is deprecated in Ocata and its use may result in errors in future releases. As 'project_id' is provided, the 'tenant_id' argument will be ignored.
  warnings.warn(msg)
Removing 149.165.171.188 from 
/Users/marc/.ssh/known_hosts:40: invalid line
/Users/marc/.ssh/known_hosts:66: invalid line
# Host 149.165.171.188 found: line 67
/Users/marc/.ssh/known_hosts is not a valid known_hosts file.
Not replacing existing known_hosts file because of errors
```

The issue is that my known_hosts file has two entries like this:

```
 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlz...
```

It is hard to see, but the line starts with a space. I have no idea why that space is there.

**Comment by ksuderman** [comment]
Delete the line with the leading space.  The jetstream script simply calls `ssh-keygen -D <ip-address>` and apparently ssh-keygen doesn't like a malformed known_hosts file.

**Comment by marcverhagen** [comment]
Yeah, I had done that and that worked of course. The funny thing is that I first removed the leading space and that did not fix the problem. The problem is not the leading space but that the first of the three required fields in the known_hosts line is empty and I wondered what past mishap caused that.

**Comment by marcverhagen** [comment]
By the way, removing those lines fixed issue https://github.com/lappsgrid-incubator/jetstream-scripts/issues/5.
